appearance:
  default: light
  switcher: true

theme:
  colorPalettes:
    default:
      light:
        - "#118dff"
        - "#107c10"
        - "#ca5010"
        - "#d13438"
        - "#12239e"
        - "#008272"
        - "#8764b8"
        - "#d9b300"
        - "#605e5c"
        - "#94a3b8"
      dark:
        - "#5794f2"
        - "#73bf69"
        - "#ff9830"
        - "#f2495c"
        - "#8ab8ff"
        - "#37872d"
        - "#b877d9"
        - "#fade2a"
        - "#9fa0a2"
        - "#6e6e6e"
  colorScales:
    default:
      light:
        - "#e8f4fd"
        - "#118dff"
      dark:
        - "#1f2428"
        - "#5794f2"
  colors:
    primary:
      light: "#118dff"
      dark: "#5794f2"
    accent:
      light: "#008272"
      dark: "#73bf69"
    base-100:
      light: "#ffffff"
      dark: "#181b1f"
    base-200:
      light: "#f3f2f1"
      dark: "#111217"
    base-300:
      light: "#edebe9"
      dark: "#2a2a2e"
    base-content:
      light: "#252423"
      dark: "#d8d9da"
    info:
      light: "#118dff"
      dark: "#5794f2"
    positive:
      light: "#107c10"
      dark: "#73bf69"
    warning:
      light: "#ca5010"
      dark: "#ff9830"
    negative:
      light: "#d13438"
      dark: "#f2495c"

plugins:
  components:
    "@evidence-dev/core-components": {}

  datasources:
    "@evidence-dev/bigquery": { }
    "@evidence-dev/csv": { }
    "@evidence-dev/databricks": { }
    "@evidence-dev/duckdb": { }
    "@evidence-dev/mssql": { }
    "@evidence-dev/mysql": { }
    "@evidence-dev/postgres": { }
    "@evidence-dev/source-javascript": { }
    "@evidence-dev/snowflake": { }
    "@evidence-dev/sqlite": { }
    "@evidence-dev/trino": { }
    "@evidence-dev/motherduck": { }
